name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install poetry
      uses: abatilo/actions-poetry@v4
    - name: Install dependencies
      run: |
        poetry install
    - name: Run linter
      run: |
        poetry run ruff check .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install poetry
      uses: abatilo/actions-poetry@v4
    - name: Install dependencies
      run: |
        poetry install
    - name: Run test
      run: |
        poetry run pytest ./tests -vv
